$(function(){
	$(".btn_view_all").click(function(){
			if(!$(this).hasClass("active"))
			{
				$(this).addClass("active");
				$(".btn_view").each(function(){
					$(this).addClass("active");
					$(this).removeClass("btn-default");
					$(this).addClass("btn-success");
					$(this).next().val(1);
				});
			}else{
				$(this).removeClass("active");
				$(".btn_view").each(function(){
					$(this).removeClass("active");
					$(this).addClass("btn-default");
					$(this).removeClass("btn-success");
					$(this).next().val(0);
					var id = $(this).attr("data");
					$("#"+id+"_all").removeClass("active").addClass("btn-default").removeClass("btn-success");
				});
			}
		});
		$(".btn_create_all").click(function(){
			if(!$(this).hasClass("active"))
			{
				$(this).addClass("active");
				$(".btn_create").each(function(){
					$(this).addClass("active");
					$(this).removeClass("btn-default");
					$(this).addClass("btn-success");
					$(this).next().val(1);
				});
			}else{
				$(this).removeClass("active");
				$(".btn_create").each(function(){
					$(this).removeClass("active");
					$(this).addClass("btn-default");
					$(this).removeClass("btn-success");
					$(this).next().val(0);
					var id = $(this).attr("data");
					$("#"+id+"_all").removeClass("active").addClass("btn-default").removeClass("btn-success");
				});
			}
		});
		$(".btn_edit_all").click(function(){
			if(!$(this).hasClass("active"))
			{
				$(this).addClass("active");
				$(".btn_edit").each(function(){
					$(this).addClass("active");
					$(this).removeClass("btn-default");
					$(this).addClass("btn-success");
					$(this).next().val(1);
				});
			}else{
				$(this).removeClass("active");
				$(".btn_edit").each(function(){
					$(this).removeClass("active");
					$(this).addClass("btn-default");
					$(this).removeClass("btn-success");
					$(this).next().val(0);
					var id = $(this).attr("data");
					$("#"+id+"_all").removeClass("active").addClass("btn-default").removeClass("btn-success");
				});
			}
		});
		$(".btn_delete_all").click(function(){
			if(!$(this).hasClass("active"))
			{
				$(this).addClass("active");
				$(".btn_delete").each(function(){
					$(this).addClass("active");
					$(this).removeClass("btn-default");
					$(this).addClass("btn-success");
					$(this).next().val(1);
				});
			}else{
				$(this).removeClass("active");
				$(".btn_delete").each(function(){
					$(this).removeClass("active");
					$(this).addClass("btn-default");
					$(this).removeClass("btn-success");
					$(this).next().val(0);
					var id = $(this).attr("data");
					$("#"+id+"_all").removeClass("active").addClass("btn-default").removeClass("btn-success");
				});
			}
		});
		$(".btn_all_all").click(function(){
			if(!$(this).hasClass("active"))
			{
				$(this).addClass("active");
				$(".btn_view").each(function(){
					$(this).addClass("active");
					$(this).removeClass("btn-default");
					$(this).addClass("btn-success");
					$(this).next().val(1);
				});
				$(".btn_create").each(function(){
					$(this).addClass("active");
					$(this).removeClass("btn-default");
					$(this).addClass("btn-success");
					$(this).next().val(1);
				});
				$(".btn_edit").each(function(){
					$(this).addClass("active");
					$(this).removeClass("btn-default");
					$(this).addClass("btn-success");
					$(this).next().val(1);
				});
				$(".btn_delete").each(function(){
					$(this).addClass("active");
					$(this).removeClass("btn-default");
					$(this).addClass("btn-success");
					$(this).next().val(1);
				});
				$(".btn_all").each(function(){
					$(this).addClass("active");
					$(this).removeClass("btn-default");
					$(this).addClass("btn-success");
				});
			}else{
				$(this).removeClass("active");
				$(".btn_view").each(function(){
					$(this).removeClass("active");
					$(this).addClass("btn-default");
					$(this).removeClass("btn-success");
					$(this).next().val(0);
				});
				$(".btn_create").each(function(){
					$(this).removeClass("active");
					$(this).addClass("btn-default");
					$(this).removeClass("btn-success");
					$(this).next().val(0);
				});
				$(".btn_edit").each(function(){
					$(this).removeClass("active");
					$(this).addClass("btn-default");
					$(this).removeClass("btn-success");
					$(this).next().val(0);
				});
				$(".btn_delete").each(function(){
					$(this).removeClass("active");
					$(this).addClass("btn-default");
					$(this).removeClass("btn-success");
					$(this).next().val(0);
				});
				$(".btn_all").each(function(){
					$(this).removeClass("active");
					$(this).addClass("btn-default");
					$(this).removeClass("btn-success");
				});
			}
		});
		$(".btn_view,.btn_create,.btn_edit,.btn_delete").click(function(){
			if($(this).hasClass("active"))
			{
				$(this).removeClass("active");
				$(this).addClass("btn-default");
				$(this).removeClass("btn-success");
				$(this).next().val(0);
				var id = $(this).attr("data");
				$("#"+id+"_all").removeClass("active").addClass("btn-default").removeClass("btn-success");
			}else{
				$(this).addClass("active");
				$(this).removeClass("btn-default");
				$(this).addClass("btn-success");
				$(this).next().val(1);
			}
		});
		$(".btn_all").click(function(){
			if($(this).hasClass("active"))
			{
				$(this).removeClass("active");
				$(this).addClass("btn-default");
				$(this).removeClass("btn-success");
				var all = $(this);
				//Delete
				all.prev().val(0);
				all.prev().prev()
				.removeClass("active").addClass("btn-default").removeClass("btn-success");
				//Edit
				all.prev().prev().prev().val(0);
				all.prev().prev().prev().prev()
				.removeClass("active").addClass("btn-default").removeClass("btn-success");
				//Create
				all.prev().prev().prev().prev().prev().val(0);
				all.prev().prev().prev().prev().prev().prev()
				.removeClass("active").addClass("btn-default").removeClass("btn-success");
				//View
				all.prev().prev().prev().prev().prev().prev().prev().val(0);
				all.prev().prev().prev().prev().prev().prev().prev().prev()
				.removeClass("active").addClass("btn-default").removeClass("btn-success");
			}else{
				$(this).addClass("active");
				$(this).removeClass("btn-default");
				$(this).addClass("btn-success");
				var all = $(this);
				//Delete
				all.prev().val(1);
				all.prev().prev()
				.addClass("active").removeClass("btn-default").addClass("btn-success");
				//Edit
				all.prev().prev().prev().val(1);
				all.prev().prev().prev().prev()
				.addClass("active").removeClass("btn-default").addClass("btn-success");
				//Create
				all.prev().prev().prev().prev().prev().val(1);
				all.prev().prev().prev().prev().prev().prev()
				.addClass("active").removeClass("btn-default").addClass("btn-success");
				//View
				all.prev().prev().prev().prev().prev().prev().prev().val(1);
				all.prev().prev().prev().prev().prev().prev().prev().prev()
				.addClass("active").removeClass("btn-default").addClass("btn-success");
			}
		});
});